on: push

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - run: pip install . pyinstaller
    - run: |
        pyinstaller --console --clean --collect-data jddesk.display --name jddesk .\jddesk\__main__.py
        pyinstaller --console --clean --name setup_config .\jddesk\setup_config.py
        pyinstaller --console --clean --name display_server .\jddesk\display\__main__.py
        copy .\dist\setup_config\setup_config.exe .\dist\jddesk
        copy .\dist\display_server\display_server.exe .\dist\jddesk
    - uses: actions/upload-artifact@v3
      with:
        name: jddesk
        path: dist/jddesk