on: push

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - run: pip install . nuitka
    - run: |
        nuitka --standalone --output-dir=dist/jddesk --include-package-data=jddesk -o jddesk.exe --remove-output --assume-yes-for-downloads .\jddesk\__main__.py
        copy .\windows\* .\dist\jddesk
    - uses: actions/upload-artifact@v3
      with:
        name: jddesk-windows
        path: dist/jddesk